Issue creation
Kozea/gibolt pull request #92
Opened 2017-12-29 10:19 UTC by SamR1

**Actions effectuées:**
* Quelques améliorations suite retours de Clément : dans le cas où le projet ainsi que la milestone sont sélectionnés, les champs relatifs sont grisés (dans ce cas, seules les données du repo sélectionné sont chargées et non pas l'ensemble des répos).
![capture du 2017-12-29 10-44-45](https://user-images.githubusercontent.com/3525167/34434374-09f3e520-ec86-11e7-9db8-d48914de0750.png)
* Ajout d'un [éditeur WYSIWYG](https://jpuri.github.io/react-draft-wysiwyg/) avec export en markdown (cf. capture d'écran ci-dessus).
Note:   
   * Seules les fonctionnalités de l'éditeur compatibles avec la notation **Markdown** de **GitHub** sont conservées (par rapport à la version HTML).  
   * L'import d'image n'est pas activé (visiblement [l'ajout d'image ne semble pas prévu nativement/simplement dans l'API](https://stackoverflow.com/questions/28703544/create-an-issue-with-image-via-github-api)). Une des solutions serait de stocker les images sur le serveur sur lequel est hébergé **Gibolt** et d'utiliser le lien de l'image à la place lors de la création du ticket. Toutefois il reste possible d'ajouter des images (hébergées ailleurs) directement via la notation **Markdown**.
* Corrections mineures

2017-12-29 13:21 UTC, grewn0uille requested changes

2017-12-29 13:21 UTC, grewn0uille commented on lib/backend/routes/github.py
> +        'milestone_number': (
le response créé dans create_a_ticket et celui dans update_a_ticket sont pareil, ca pourrait être bien de sortir la création du response de ces 2 fonctions pour éviter de la duplication de code

2017-12-29 13:21 UTC, grewn0uille commented on lib/backend/routes/github.py
> +        label_request = github.request('PATCH',
passer à la ligne avant le 'PATCH'

2017-12-29 14:08 UTC, SamR1 commented on lib/backend/routes/github.py
> +        'milestone_number': (
done sur les 3 fonctions : 
* get_a_ticket
* create_a_ticket
* update_a_ticket

(à noter que pour le moment **get_a_ticket** et **update_a_ticket** ne sont pas appelées, par ailleurs le retour de la fonction **create_a_ticket** n'est pas exploité étant donné qu'il y a redirection après création avec succès du ticket)

2017-12-29 14:08 UTC, SamR1 commented on lib/backend/routes/github.py
> +        label_request = github.request('PATCH',
done

2017-12-29 14:24 UTC, grewn0uille approved these changes

2018-01-02 13:40 UTC, yobuntu commented
Bonne idée d'avoir factoriser le formatage d'un ticket.
A voir si on peut faire de même avec la gestion des exceptions github (sans faire un truc trop compliqué), pour le moment j'ai pas d'idée, mais j'y réfléchi.

2018-01-02 13:40 UTC, merged