CRUD Circles & Roles
Kozea/gibolt pull request #93
Opened 2018-01-02 15:36 UTC by rojinpolat

**Actions réalisées:**

### 1. CRUD Circles 
Il est possible de:
- créer un cercle:
![image](https://user-images.githubusercontent.com/19991097/34488701-c41ad89a-efd9-11e7-9455-5528ca294161.png)
On accède à cette page par l’onglet « Circles » en cliquant sur le bouton « Add a circle ». Tous les champs sont obligatoires. 
- afficher la liste des cercles et les données d'un cercle:
![image](https://user-images.githubusercontent.com/19991097/34488714-d36b426c-efd9-11e7-8cdf-35fc0094c4e8.png)
- mettre à jour les données d'un cercle : en cliquant sur « Update » le formulaire de mise à jour apparaît.
- supprimer un cercle

### 2. CRUD Roles
Il est possible de:
- créer un rôle à partir d'un cercle sélectionné :
![image](https://user-images.githubusercontent.com/19991097/34488732-e4313408-efd9-11e7-98e8-c0809036ccad.png)
- afficher la liste des rôles dans un onglet: cet onglet est provisoire, il faudra le modifier ou l’enlever prochainement en fonction du besoin (par exemple: lister les utilisateurs et afficher les rôles par utilisateur )
- afficher les données d'un rôle ( en cliquant sur le rôle dans la liste)
- mettre à jour les données d'un rôle: en cliquant sur « Update », le formulaire de mise à jour apparaît.
- supprimer un rôle

2018-01-02 15:50 UTC, grewn0uille requested changes

2018-01-02 15:50 UTC, grewn0uille commented on lib/frontend/src/components/Circles.sass
>    border: none
ordre alphabetique plz

2018-01-02 15:50 UTC, grewn0uille commented on lib/frontend/src/components/Createcircle.sass
> +  border: none
ordre alphabetique plz

2018-01-02 15:50 UTC, grewn0uille commented on lib/frontend/src/components/Roles.sass
> +    display: flex
ordre alphabetique plz

2018-01-03 08:27 UTC, rojinpolat commented on lib/frontend/src/components/Circles.sass
>    border: none
corrigé

2018-01-03 08:28 UTC, rojinpolat commented on lib/frontend/src/components/Createcircle.sass
> +  border: none
corrigé

2018-01-03 08:28 UTC, rojinpolat commented on lib/frontend/src/components/Roles.sass
> +    display: flex
corrigé

2018-01-03 08:56 UTC, SamR1 commented on lib/backend/api/models.py
> +    role_checklist = Column(String)
Les checklists (et les indicateurs) sont portés par la table '**Item**', cf. [modèle de donnée](https://github.com/Kozea/gibolt/issues/52#issuecomment-351445299).
Modèle à mettre à jour, s'il faut gérer les checklists directement dans la table '**Role**'.

2018-01-03 10:40 UTC, rojinpolat commented on lib/backend/api/models.py
> +    role_checklist = Column(String)
corrigé

2018-01-03 10:43 UTC, grewn0uille approved these changes

2018-01-03 16:46 UTC, merged