Création rapport
Kozea/gibolt pull request #95
Opened 2018-01-04 13:14 UTC by SamR1

Actions réalisées:
* Gestion des compte-rendus des réunion dans Gibolt (partiel)
   * accès aux rapports via la page du cercle
![capture du 2018-01-04 14-07-28](https://user-images.githubusercontent.com/3525167/34564823-a051687c-f158-11e7-9f4b-b758d0e02262.png)
![capture du 2018-01-04 14-01-41](https://user-images.githubusercontent.com/3525167/34564648-d0cd3ea0-f157-11e7-9390-783cb0b81d8a.png)
Les **cercle** et **type de réunion** sont présélectionnés selon le bouton cliqué, mais cette page permet d'accèder à tous les compte-rendus, pour tous les cercles, via les selects. 
Elle permet également de visualiser un rapport et d'accéder à la création d'un rapport quand les 2 selects sont renseignés (le bouton **Add a report** est alors actif).
   * creation d'un rapport (**partiel**)
![capture du 2018-01-04 14-04-24](https://user-images.githubusercontent.com/3525167/34564727-306f8c5a-f158-11e7-985e-06579d509640.png)
**⚠️ feature incomplète: ne gère pas ni checklists ni les indicateurs**
   * visualisation d'un rapport
![capture du 2018-01-04 14-06-03](https://user-images.githubusercontent.com/3525167/34564783-6bf76e6e-f158-11e7-8736-24dc5633ae88.png)
* merge de la branche master
* correction du style des pages pour ajouter un cercle ou un rôle

2018-01-04 14:14 UTC, grewn0uille requested changes

2018-01-04 14:14 UTC, grewn0uille commented on lib/frontend/src/components/Circle.sass
>    border: none
ordre alpha

2018-01-04 14:14 UTC, grewn0uille commented on lib/frontend/src/components/Meetings.sass
> +    display: flex
ordre alpha

2018-01-04 14:27 UTC, yobuntu commented
- Ajouter les sous-cercles dans la vue cercle
- Permettre la création d'une réunion directement

2018-01-04 15:37 UTC, SamR1 commented on lib/frontend/src/components/Meetings.sass
> +    display: flex
done

2018-01-04 15:40 UTC, SamR1 commented
- Ajouter les sous-cercles dans la vue cercle : done
- Permettre la création d'une réunion directement done

Remarque: pour le moment il n'est pas possible de modifier/supprimer un rapport => confirmer si ce comportement convient

2018-01-04 16:32 UTC, grewn0uille approved these changes

2018-01-04 16:33 UTC, SamR1 commented on lib/frontend/src/components/Circle.sass
>    border: none
version antérieure du composant, corrigée dans cette pull request

2018-01-04 16:53 UTC, SamR1 commented
Correction: on ne peut pas supprimer un cercle s'il existe des rapports associés.

A noter: 
* il est possible de créer des rapports vides => à corriger (sera traité lors de l'intégration des checklists et items, le composant **MarkdowEditor** étant en cours de modification)
* composant **Circle** à refactoriser en sous composant (sera fait sur une nouvelle branche)

2018-01-05 08:44 UTC, SamR1 commented
Ajout de la correction de la recherche dans les tickets

2018-01-05 09:18 UTC, merged